# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dreamai_resume',
                'doc_host': 'https://HamzaFarhan.github.io',
                'git_url': 'https://github.com/HamzaFarhan/dreamai_resume',
                'lib_path': 'dreamai_resume'},
  'syms': { 'dreamai_resume.core': {'dreamai_resume.core.foo': ('core.html#foo', 'dreamai_resume/core.py')},
            'dreamai_resume.imports': {},
            'dreamai_resume.ocr': { 'dreamai_resume.ocr.align_images': ('ocr.html#align_images', 'dreamai_resume/ocr.py'),
                                    'dreamai_resume.ocr.all_cases': ('ocr.html#all_cases', 'dreamai_resume/ocr.py'),
                                    'dreamai_resume.ocr.bbox_in_config': ('ocr.html#bbox_in_config', 'dreamai_resume/ocr.py'),
                                    'dreamai_resume.ocr.cleanup_text': ('ocr.html#cleanup_text', 'dreamai_resume/ocr.py'),
                                    'dreamai_resume.ocr.dai_ocr': ('ocr.html#dai_ocr', 'dreamai_resume/ocr.py'),
                                    'dreamai_resume.ocr.hand_ocr': ('ocr.html#hand_ocr', 'dreamai_resume/ocr.py'),
                                    'dreamai_resume.ocr.pdf_to_imgs': ('ocr.html#pdf_to_imgs', 'dreamai_resume/ocr.py'),
                                    'dreamai_resume.ocr.remove_ns': ('ocr.html#remove_ns', 'dreamai_resume/ocr.py'),
                                    'dreamai_resume.ocr.split_words': ('ocr.html#split_words', 'dreamai_resume/ocr.py')}}}
