# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dreamai_resume',
                'doc_host': 'https://HamzaFarhan.github.io',
                'git_url': 'https://github.com/HamzaFarhan/dreamai_resume',
                'lib_path': 'dreamai_resume'},
  'syms': {'dreamai_resume.core': {'dreamai_resume.core.foo': ('core.html#foo', 'dreamai_resume/core.py')}}}
